version: '3.8'
services:
  metrofitness-db:
    container_name: metrofitness-db
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: metrofitness-nest
      PGDATA: /var/lib/postgresql/data
    networks:
      metrofitnessnet:
        ipv4_address: 192.168.10.100
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  
networks:
  metrofitnessnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
volumes:
  postgres:
  minio:
